version: '3'
services:
  postgresql-master:
    image: postgres:13
    container_name: postgresql-master
    restart: always
    volumes:
        - ./data/master:/var/lib/postgresql/data
        - ./postgres-master.conf:/etc/postgres/postgresql.conf
        - ./pg_hba-master.conf:/etc/postgres/pg_hba.conf
        - ./master.sh:/docker-entrypoint-initdb.d/init-master.sh
    command: postgres -c config_file=/etc/postgres/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_PASSWORD=postgresPass'
      - 'POSTGRES_DB=my_default_database'

  postgresql-slave:
    image: postgres:13
    container_name: postgresql-slave
    restart: always
    volumes:
        - ./data/slave:/var/lib/postgresql/data
        - ./slave.sh:/docker-entrypoint-initdb.d/init-slave.sh
    ports:
      - "5433:5432"
    environment:
      - 'POSTGRES_PASSWORD=postgresPass'

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgresPass@192.168.1.102:5432/shop?sslmode=disable"
    links:
      - postgresql-master
      - prometheus
